apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  annotations:
    metallb.universe.tf/allow-shared-ip: default
  labels:
    app: tig
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.111
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: tig
    tier: grafana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app: tig
spec:
  selector:
    matchLabels:
      app: tig
      tier: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tig
        tier: grafana
    spec:
      containers:
      - image: grafana_image
        imagePullPolicy: Never
        name: grafana
        ports:
        - containerPort: 3000
      #   volumeMounts:
      #   - name: influx-pv
      #     mountPath: "/var/lib/influx"
      # volumes:
      # - name: influx-pv
      #   persistentVolumeClaim:
      #     claimName: influx-pv-claim