# apiVersion: v1
# kind: Service
# metadata:
#   name: telegraf-service
#   labels:
#     app: tig
# spec:
#   type: ClusterIP
#   ports:
#     - port: 3306
#       targetPort: 3306
#       protocol: TCP
#   selector:
#     app: tig
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: telegraf-pv
#   labels:
#     type: local
# spec:
#   storageClassName: fast
#   capacity:
#     storage: 500Mi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/var/lib/telegraf"
#   claimRef:
#     name: telegraf-pvc
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: telegraf-pv-claim
#   labels:
#     app: telegraf
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-deployment
  labels:
    app: tig
spec:
  selector:
    matchLabels:
      app: tig
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tig
        tier: telegraf
    spec:
      containers:
      - image: telegraf_image
        imagePullPolicy: Never
        resources:
          limits:
        name: telegraf
      #   volumeMounts:
      #   - name: telegraf-pv
      #     mountPath: "/var/lib/telegraf"
      # volumes:
      # - name: telegraf-pv
      #   persistentVolumeClaim:
      #     claimName: telegraf-pv-claim